name: Backup JSON
on:
  schedule:
    - cron: '0 0 * * *' # every midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Auto backup JSON"
          git push